bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database db_test;' -U postgres
  - cp config/database.travis.yml config/database.yml

#env:
#  - MOZ_HEADLESS=1
#addons:
#  firefox: latest


dist: trusty
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
