language: ruby


#dist: trusty
addons:
  chrome: stable
#before_install:
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

#env:
#  - MOZ_HEADLESS=1
#addons:
#  firefox: latest



cache: bundler
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database db_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rails assets:precompile
  - yarn install
  - bundle exec rails webpacker:compile

