language: ruby

addons:
  chrome: stable

cache: bundler
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database db_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rails assets:precompile
  - yarn install
  - bundle exec rails webpacker:compile

